# Generated by Django 5.0 on 2025-06-09 20:43

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CinemaHall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rows', models.IntegerField()),
                ('seats_per_row', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoyaltyTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold')], max_length=20)),
                ('points_required', models.PositiveIntegerField()),
                ('discount_percentage', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['points_required'],
            },
        ),
        migrations.RunPython(
            code=lambda apps, schema_editor: apps.get_model('movie', 'LoyaltyTier').objects.bulk_create([
                apps.get_model('movie', 'LoyaltyTier')(name='bronze', points_required=1500, discount_percentage=3),
                apps.get_model('movie', 'LoyaltyTier')(name='silver', points_required=3000, discount_percentage=5),
                apps.get_model('movie', 'LoyaltyTier')(name='gold', points_required=4500, discount_percentage=7),
            ]),
            reverse_code=lambda apps, schema_editor: apps.get_model('movie', 'LoyaltyTier').objects.all().delete(),
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('release_date', models.DateField(default=django.utils.timezone.now)),
                ('description', models.TextField()),
                ('directors', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('duration', models.IntegerField(blank=True, null=True, verbose_name='Duration in minutes')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='movie_posters/')),
                ('horizontal_poster', models.ImageField(blank=True, null=True, upload_to='movie_horizontal_posters/')),
                ('trailer_link', models.URLField(blank=True, null=True)),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('language', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('genres', models.ManyToManyField(related_name='movies', to='movie.genre')),
            ],
        ),
        migrations.CreateModel(
            name='HomepageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Homepage Settings', max_length=100)),
                ('coming_soon_movies', models.ManyToManyField(blank=True, limit_choices_to={'is_active': True, 'release_date__gt': datetime.date(2025, 6, 9)}, related_name='coming_soon_on_homepage', to='movie.movie')),
                ('featured_movies', models.ManyToManyField(blank=True, limit_choices_to={'is_active': True}, related_name='featured_on_homepage', to='movie.movie')),
                ('now_playing_movies', models.ManyToManyField(blank=True, limit_choices_to={'is_active': True, 'release_date__lte': datetime.date(2025, 6, 9)}, related_name='now_playing_on_homepage', to='movie.movie')),
                ('top_rated_movies', models.ManyToManyField(blank=True, limit_choices_to={'is_active': True}, related_name='top_rated_on_homepage', to='movie.movie')),
            ],
            options={
                'verbose_name': 'Homepage Settings',
                'verbose_name_plural': 'Homepage Settings',
            },
        ),
        migrations.CreateModel(
            name='MovieSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('price', models.DecimalField(decimal_places=2, default=10.0, max_digits=6)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='movie.cinemahall')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='movie.movie')),
            ],
            options={
                'ordering': ['date', 'time'],
                'unique_together': {('movie', 'hall', 'date', 'time')},
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booked_seats', models.JSONField(default=list)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='movie.moviesession')),
            ],
            options={
                'ordering': ['-booking_date'],
            },
        ),
        migrations.CreateModel(
            name='UserLoyalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('total_earned_points', models.PositiveIntegerField(default=0)),
                ('tier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='movie.loyaltytier')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PointTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('transaction_type', models.CharField(choices=[('earn', 'Points Earned'), ('spend', 'Points Spent')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='point_transactions', to='movie.booking')),
                ('user_loyalty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='movie.userloyalty')),
            ],
        ),
    ]
