# Generated by Django 5.0 on 2025-06-01 12:33

from django.db import migrations
from django.utils.text import slugify

def create_initial_genres(apps, schema_editor):
    Genre = apps.get_model('movie', 'Genre')
    genres = [
        'Action',
        'Adventure',
        'Comedy',
        'Drama',
        'Fantasy',
        'Horror',
        'Mystery',
        'Romance',
        'Sci-Fi',
        'Thriller',
        'Animation',
        'Documentary',
        'Family',
        'Crime',
        'Biography',
        'History',
        'War',
        'Musical',
        'Sport',
        'Western'
    ]
    
    for genre_name in genres:
        slug = slugify(genre_name)
        Genre.objects.get_or_create(
            name=genre_name,
            defaults={'slug': slug}
        )

def remove_initial_genres(apps, schema_editor):
    Genre = apps.get_model('movie', 'Genre')
    Genre.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_genre_remove_movie_genre_remove_movie_image_and_more'),
    ]

    operations = [
        migrations.RunPython(create_initial_genres, remove_initial_genres),
    ]
