# Generated by Django 5.0 on 2025-06-01 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_create_initial_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='subscription_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='movie',
            name='tags',
            field=models.ManyToManyField(blank=True, to='movie.tag'),
        ),
    ]
