# Generated by Django 5.0 on 2025-06-01 13:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_movie_subscription_required_alter_movie_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Homepage Settings', max_length=100)),
                ('coming_soon_movies', models.ManyToManyField(blank=True, limit_choices_to={'is_active': True, 'release_date__gt': datetime.date(2025, 6, 1)}, related_name='coming_soon_on_homepage', to='movie.movie')),
                ('featured_movies', models.ManyToManyField(blank=True, limit_choices_to={'is_active': True}, related_name='featured_on_homepage', to='movie.movie')),
                ('now_playing_movies', models.ManyToManyField(blank=True, limit_choices_to={'is_active': True, 'release_date__lte': datetime.date(2025, 6, 1)}, related_name='now_playing_on_homepage', to='movie.movie')),
                ('special_screenings', models.ManyToManyField(blank=True, limit_choices_to={'is_active': True, 'is_special_screening': True}, related_name='special_screenings_on_homepage', to='movie.movie')),
            ],
            options={
                'verbose_name': 'Homepage Settings',
                'verbose_name_plural': 'Homepage Settings',
            },
        ),
    ]
