# Generated by Django 5.0 on 2025-06-01 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_homepagesettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagesettings',
            name='special_screenings',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='is_special_screening',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='screening_type',
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='top_rated_movies',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_active': True}, related_name='top_rated_on_homepage', to='movie.movie'),
        ),
    ]
