# Generated by Django 5.0 on 2025-06-02 17:19

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_remove_homepagesettings_special_screenings_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='moviesession',
            unique_together={('movie', 'date', 'time')},
        ),
        migrations.AddField(
            model_name='moviesession',
            name='available_seats',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='moviesession',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='moviesession',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='moviesession',
            name='total_seats',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='moviesession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='coming_soon_movies',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_active': True, 'release_date__gt': datetime.date(2025, 6, 2)}, related_name='coming_soon_on_homepage', to='movie.movie'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='now_playing_movies',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_active': True, 'release_date__lte': datetime.date(2025, 6, 2)}, related_name='now_playing_on_homepage', to='movie.movie'),
        ),
        migrations.AlterField(
            model_name='moviesession',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=6),
        ),
        migrations.RemoveField(
            model_name='moviesession',
            name='hall',
        ),
    ]
