# Generated by Django 5.0 on 2025-06-02 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0009_alter_moviesession_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviesession',
            name='rows',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='moviesession',
            name='seats_per_row',
            field=models.IntegerField(default=10),
        ),
    ]
