# Generated by Django 5.0 on 2025-06-02 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0010_moviesession_rows_moviesession_seats_per_row'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviesession',
            name='hall',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='movie.cinemahall'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='moviesession',
            unique_together={('movie', 'hall', 'date', 'time')},
        ),
        migrations.RemoveField(
            model_name='moviesession',
            name='available_seats',
        ),
        migrations.RemoveField(
            model_name='moviesession',
            name='rows',
        ),
        migrations.RemoveField(
            model_name='moviesession',
            name='seats_per_row',
        ),
        migrations.RemoveField(
            model_name='moviesession',
            name='total_seats',
        ),
    ]
