# Generated by Django 5.0 on 2025-06-02 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0011_alter_moviesession_unique_together_moviesession_hall_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='seats',
        ),
        migrations.AddField(
            model_name='booking',
            name='booked_seats',
            field=models.JSONField(default=list),
        ),
        migrations.DeleteModel(
            name='Seat',
        ),
    ]
