# Generated by Django 5.0 on 2025-06-02 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0012_remove_booking_seats_booking_booked_seats_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviesession',
            name='booked_seats',
            field=models.JSONField(default=list),
        ),
    ]
