# Generated by Django 5.0 on 2025-06-03 13:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0013_moviesession_booked_seats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviesession',
            name='booked_seats',
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='coming_soon_movies',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_active': True, 'release_date__gt': datetime.date(2025, 6, 3)}, related_name='coming_soon_on_homepage', to='movie.movie'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='now_playing_movies',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_active': True, 'release_date__lte': datetime.date(2025, 6, 3)}, related_name='now_playing_on_homepage', to='movie.movie'),
        ),
    ]
