# Generated by Django 5.0 on 2025-06-03 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_create_loyalty_tiers'),
        ('movie', '0015_loyaltytier_pointtransaction_userloyalty'),
    ]

    operations = [
    ]
