# Generated by Django 5.0 on 2025-06-03 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0016_merge_20250603_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='userloyalty',
            name='total_earned_points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
