# Generated by Django 5.0 on 2025-06-03 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0017_userloyalty_total_earned_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='subscription_required',
        ),
    ]
