# Generated by Django 5.0 on 2025-06-04 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0019_alter_homepagesettings_coming_soon_movies_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pointtransaction',
            name='user',
        ),
        migrations.AddField(
            model_name='pointtransaction',
            name='user_loyalty',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='movie.userloyalty'),
            preserve_default=False,
        ),
    ]
