# Generated by Django 5.0 on 2025-06-04 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0020_remove_pointtransaction_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cinemahall',
            name='total_seats',
        ),
        migrations.AddField(
            model_name='movie',
            name='horizontal_poster',
            field=models.ImageField(blank=True, null=True, upload_to='movie_horizontal_posters/'),
        ),
    ]
