# Generated by Django 5.0 on 2025-06-04 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0021_remove_cinemahall_total_seats_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
