# Generated by Django 5.0 on 2025-06-09 16:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0022_remove_movie_tags_delete_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagesettings',
            name='coming_soon_movies',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_active': True, 'release_date__gt': datetime.date(2025, 6, 9)}, related_name='coming_soon_on_homepage', to='movie.movie'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='now_playing_movies',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_active': True, 'release_date__lte': datetime.date(2025, 6, 9)}, related_name='now_playing_on_homepage', to='movie.movie'),
        ),
    ]
