# Generated by Django 5.0 on 2025-06-04 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='watchlist',
        ),
    ]
